### ISSUE TITLE
Object of type TaxTable is not JSON serializable

### ISSUE THREAD

**Issue by innir** [loftx/gnucash-rest#8]
Hi,

calling the endpoint `/bills`, I get the following error:

```
[2019-10-08 09:16:37,233] ERROR in app: Exception on /bills [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "~/gnucash-rest/gnucash_rest/__init__.py", line 381, in api_bills
    return Response(json.dumps(bills), mimetype='application/json')
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TaxTable is not JSON serializable
127.0.0.1 - - [08/Oct/2019 09:16:37] "GET /bills HTTP/1.1" 500 -
127.0.0.1 - - [08/Oct/2019 09:17:28] "GET /accounts HTTP/1.1" 200 -
```

Might that be related to the fact that my currency is EUR and but GBP?

Everything else seems to work - I only see errors when bills come into play.

```
$ gnucash --version
GnuCash 3.7
Build ID: 3.7+(2019-09-07)
```

**Comment by loftx** [comment]
Hi innir, thanks for reporting this.

I'm afraid I haven't used the GnuCash TaxTable functionality before so it's likely that if you use this that's what's causing the issue.

I expect you can work around this by commenting out the line:

simple_entry['bill_tax_table'] = entry.GetBillTaxTable()

In https://github.com/loftx/gnucash-rest/blob/d6d93f4da45f0badd6a0ca5138b8518904f337e1/gnucash_rest/gnucash_simple.py#L275

I will do more investigation into this and get back to you when I have a solution in place.

Kind regards,

Tom

**Comment by innir** [comment]
@loftx thanks, that works - but now the tax entry in the bills is missing:

![grafik](https://user-images.githubusercontent.com/5419701/66557385-11ccf080-eb52-11e9-9a25-a4d913de3b26.png)

**Comment by innir** [comment]
Added a quite simple solution in PR #10:

![grafik](https://user-images.githubusercontent.com/5419701/66562494-14ccde80-eb5c-11e9-94e2-314fdb249cb2.png)

**Comment by loftx** [comment]
Hi @innir , After looking into this further I've commited a fix along the lines of https://github.com/loftx/gnucash-rest/issues/8#issuecomment-540463232.

While it is possible to process some of the tax table information, this isn't yet fully exposed in the python bindings as far as I can tell, so it's not possible to retrieve the actual tax table information from this location.

I'll close this issue, but if you need more tax table information over and above your PR let me know and I'll investigate further.
